services:
  db:
    image: postgres:15-alpine
    container_name: news-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSKEY:?Database password is required}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7-alpine
    container_name: news-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  vector_db:
    image: qdrant/qdrant:latest
    container_name: news-qdrant
    restart: unless-stopped
    ports:
      - "${VECTOR_DB_PORT:-6333}:6333"
      - "${VECTOR_DB_GRPC_PORT:-6334}:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT_ALLOW_CORS: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:5.11.0
    container_name: news-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/your_password
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 2G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

  celery_worker:
     build:
       context: .
       dockerfile: Dockerfile.celery
     container_name: news-celery-worker
     command: celery -A celery_app worker --loglevel=info
     env_file:
       - .docker.env
     volumes:
       - .:/app
       - celery_logs:/var/log/celery
       - ./last-published-data.json:/app/last-published-data.json
     depends_on:
       - db
       - cache
       - vector_db
       - neo4j

  celery_beat:
     build:
       context: .
       dockerfile: Dockerfile.celery
     container_name: news-celery-beat
     command: celery -A celery_app beat --loglevel=info
     env_file:
       - .docker.env
     volumes:
       - .:/app
       - celery_logs:/var/log/celery
       - ./last-published-data.json:/app/last-published-data.json
     depends_on:
       - celery_worker
       - cache

volumes:
  postgres_data:
    name: news-postgres-data
  pgadmin_data:
    name: news-pgadmin-data
  redis_data:
    name: news-redis-data
  qdrant_data:
    name: news-qdrant-data
  neo4j_data:
    name: news-neo4j-data
  neo4j_logs:
    name: news-neo4j-logs
  neo4j_import:
    name: news-neo4j-import
  neo4j_plugins:
    name: news-neo4j-plugins
  celery_logs:
    name: news-celery-logs

networks:
  default:
    name: news-network