services:
  db:
    image: postgres:15-alpine
    container_name: news-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSKEY:?Database password is required}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7-alpine
    container_name: news-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  vector_db:
    image: qdrant/qdrant:latest
    container_name: news-qdrant
    restart: unless-stopped
    ports:
      - "${VECTOR_DB_PORT:-6333}:6333"
      - "${VECTOR_DB_GRPC_PORT:-6334}:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT_ALLOW_CORS: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5


#  celery_worker:
#     build:
#       context: .
#       dockerfile: Dockerfile.celery
#     container_name: news-celery-worker
#     command: celery -A celery_app worker --loglevel=info
#     env_file:
#       - .docker.env
#     volumes:
#       - .:/app
#       - celery_logs:/var/log/celery
#       - ./last-published-data.json:/app/last-published-data.json
#     depends_on:
#       - db
#       - cache
#       - vector_db
#       - neo4j
#
#  celery_beat:
#     build:
#       context: .
#       dockerfile: Dockerfile.celery
#     container_name: news-celery-beat
#     command: celery -A celery_app beat --loglevel=info
#     env_file:
#       - .docker.env
#     volumes:
#       - .:/app
#       - celery_logs:/var/log/celery
#       - ./last-published-data.json:/app/last-published-data.json
#     depends_on:
#       - celery_worker
#       - cache

volumes:
  postgres_data:
    name: news-postgres-data
  pgadmin_data:
    name: news-pgadmin-data
  redis_data:
    name: news-redis-data
  qdrant_data:
    name: news-qdrant-data
  celery_logs:
    name: news-celery-logs

networks:
  default:
    name: news-network