version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: news-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSKEY:?Database password is required}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: news-pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    ports:
#      - "5050:80"
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    depends_on:
#      - db

  cache:
    image: redis:7-alpine
    container_name: news-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  vector_db:
    image: qdrant/qdrant:latest
    container_name: news-qdrant
    restart: unless-stopped
    ports:
      - "${VECTOR_DB_PORT:-6333}:6333"
      - "${VECTOR_DB_GRPC_PORT:-6334}:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT_ALLOW_CORS: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:5.11.0
    container_name: news-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/your_password
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 2G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

volumes:
  postgres_data:
    name: news-postgres-data
  pgadmin_data:
    name: news-pgadmin-data
  redis_data:
    name: news-redis-data
  qdrant_data:
    name: news-qdrant-data
  neo4j_data:
    name: news-neo4j-data
  neo4j_logs:
    name: news-neo4j-logs
  neo4j_import:
    name: news-neo4j-import
  neo4j_plugins:
    name: news-neo4j-plugins

networks:
  default:
    name: news-network